spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: q1w2e3R$
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secretKey: your-secret-key-at-least-256-bits-long-for-hs256
  validityInMilliseconds: 3600000 # 1 hour